# apiVersion: v1
# data:
#   LOG_LEVEL: info
#   NODE_ENV: development
#   PORT: "3300"
#   SERVICE_NAME: ts-prototype-pm
# kind: ConfigMap
# metadata:
#   annotations:
#     kubectl.kubernetes.io/last-applied-configuration: >
#       {"apiVersion":"v1","data":{"LOG_LEVEL":"info","NODE_ENV":"development","PORT":"3300","SERVICE_NAME":"ts-prototype-pm"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"config-staging","namespace":"staging"}}
#   creationTimestamp: 2023-03-21T03:54:45Z
#   name: prototype-config
#   namespace: sample
#   uid: f98d9b56-e757-451a-8620-2128f0c2ef42

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.namespace }}
data:
  value_a: halo
  value_b: balo  
  value_c: calo
  PORT: "3300"
  SERVICE_NAME: ts-k3s-prototype

